### ISSUE TITLE
conflict with "Right hand reviews with jkl"

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki__Extended_quick_reschedule_in_reviewer#2]
One more problem, this add on seems to prevent my other add on "Right hand reviews with jkl" from working, because whenever I delete the alternative dialog add on the right hand reviews start to work again. Any idea why that might be?

_Originally posted by @AnkiDan in https://github.com/ijgnd/anki__Extended_quick_reschedule_in_reviewer/issues/1#issuecomment-467033853_

**Comment by ijgnd** [comment]
both add-ons used an improper method to set shortcuts which works as long as only one add-on uses this method ...

I've changed my add-on. Now the other add-on should work again. This should fix it: https://github.com/ijgnd/anki__Extended_quick_reschedule_in_reviewer/commit/d07f5b25e75954d9cd00b70e8ee30d54949e1b60

@AnkiDan : Can you delete the current version of "Alternative Dialog for ReMemorize" from your add-on folder and then download/install the latetst version from https://ankiweb.net/shared/info/2107899486 . Let me know if this fixes it and if you run into other problems with this add-on

**Comment by AnkiDan** [comment]
I'm now able to configure it how I want and use the other add on while having yours installed, but unfortunately I can't get the rescheduler window to open up using the "g" key. I'd never had a problem opening it up before. FYI I don't use image occlusion add on, so it shouldn't be that that's affecting it. Sorry to keep bugging you with these issues, but you have been super helpful and I'm very grateful for offering your time to the anki community!

**Comment by ijgnd** [comment]
Did you delete all prior versions named "extended ..." or "Alterantive ..."?

&nbsp;

It works for me:

I use Anki 2.0.52. I close Anki. Then I go to my profile folder and rename the folder "addons" to "addons_temporarily_disabled". Then I restart Anki. Anki notices that there is no folder "addons" and recreates it. Then I just install my add-on and the jkl add-on:  2107899486 and 1310550323. I restart Anki. Now I can use "g" to open my reschedule window and jkl.

Try the same on your computer to rule out interference from a different add-on. The fact that I changed the name of the add-on changes the order in which its code is loaded. 

Does this minimal setup with just two add-ons work for you?

If not, report it.

If it does work with just two add-ons we know that the problem is not in the add-on itself but in an interaction with another add-on. To narrow down the conflict: Close Anki and copy one add-on over from the folder "addons_temporarily_disabled" into "addons". Restart and try again: Repeat this until you find the add-on that causes the problem. Report the name of the other add-on

**Comment by AnkiDan** [comment]
It successfully worked after following the directions in your last paragraph. Was able to import all of my old add-ons, so not sure what was causing the problem in the first place, but everything is working now. Much appreciated!
